package presentation;

import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import logic.Controller;
import logic.Member;
import logic.Payment;

/**
 *
 * @author caspe
 */
public class paymentDialog extends javax.swing.JDialog {

    Controller logic = new Controller();

    public paymentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        fillMemberComboBox();
    }

    private void fillMemberComboBox() {
        try {
            logic.updateMemberList();
            DefaultComboBoxModel model = (DefaultComboBoxModel) membersPaymentComboBox.getModel();
            model.removeAllElements();

            for (Member member : logic.memberList) {
                model.addElement(member.getID() + ", " + member.getName());
            }
            membersPaymentComboBox.setModel(model);
            //membersComboBox.setModel((ComboBoxModel<String>) logic.memberList);
        } catch (Exception ex) {
            Logger.getLogger(resultsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membersPaymentComboBox = new javax.swing.JComboBox<>();
        yearTXT = new javax.swing.JTextField();
        yearLBL = new javax.swing.JLabel();
        createPaymentBTN = new javax.swing.JButton();
        amountLBL = new javax.swing.JLabel();
        amountTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        membersPaymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        membersPaymentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membersPaymentComboBoxActionPerformed(evt);
            }
        });

        yearLBL.setText("År");

        createPaymentBTN.setText("Create Payment");
        createPaymentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPaymentBTNActionPerformed(evt);
            }
        });

        amountLBL.setText("Beløb");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createPaymentBTN)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountLBL)
                            .addComponent(yearLBL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(membersPaymentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearTXT)
                            .addComponent(amountTXT))))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(membersPaymentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountLBL)
                    .addComponent(amountTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(createPaymentBTN)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Member getMemberTest() {
        Member member = null;
        try {
            int id = Integer.parseInt(membersPaymentComboBox.getModel().getSelectedItem().toString().split(",")[0].trim());
            member = logic.getMember(id);
            
        } catch (Exception ex) {
            Logger.getLogger(paymentDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return member;
        
    }
    private void createPaymentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPaymentBTNActionPerformed
        //Member memberTest = getMemberTest();
        try {
            int id = 0;
            int memberID = Integer.parseInt(membersPaymentComboBox.getModel().getSelectedItem().toString().split(",")[0].trim());
            String paymentYear = yearTXT.getText();
            
            Member member = logic.getMember(memberID);
            //System.out.println(memberTest);
            double amount = logic.getAmountToPay(member);
            
            String date = LocalDate.now().toString();
            
            Payment payment = new Payment(id, memberID, paymentYear, amount, date);
            logic.createPayment(payment);
            
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(paymentDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createPaymentBTNActionPerformed

    private void membersPaymentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membersPaymentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membersPaymentComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                paymentDialog dialog = new paymentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLBL;
    private javax.swing.JTextField amountTXT;
    private javax.swing.JButton createPaymentBTN;
    private javax.swing.JComboBox<String> membersPaymentComboBox;
    private javax.swing.JLabel yearLBL;
    private javax.swing.JTextField yearTXT;
    // End of variables declaration//GEN-END:variables
}
