/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import logic.Controller;
import logic.Discipline;
import logic.Member;
import logic.Result;

/**
 *
 * @author caspe
 */
public class resultsDialog extends javax.swing.JDialog {

    Controller logic = new Controller();

    /**
     * Creates new form resultsDialog
     * @param parent the window where to popup "comes" from
     * @param modal tells if a popup is modal or not
     */
    public resultsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        fillMemberComboBox();
        fillDisciplinesComboBox();

        

    }
    
    private void fillMemberComboBox() {
        try {

            logic.updateMemberList();
            DefaultComboBoxModel model = (DefaultComboBoxModel) membersComboBox.getModel();
            model.removeAllElements();

            for (Member member : logic.memberList) {
                model.addElement(member.getID() + ", "+ member.getName());
            }
            membersComboBox.setModel(model);
            //membersComboBox.setModel((ComboBoxModel<String>) logic.memberList);
        } catch (Exception ex) {
            Logger.getLogger(resultsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fillDisciplinesComboBox() {
        try {
            logic.updateCategoryList();
            DefaultComboBoxModel model = (DefaultComboBoxModel) disciplinesComboBox.getModel();
            model.removeAllElements();
            
            for (Discipline discipline : logic.categoryList) {
                model.addElement(discipline.getId() + ", " + discipline.getName());
            }
            
            disciplinesComboBox.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(resultsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        membersComboBox = new javax.swing.JComboBox<>();
        disciplinesComboBox = new javax.swing.JComboBox<>();
        timeTXT = new javax.swing.JTextField();
        timeLBL = new javax.swing.JLabel();
        compBox = new javax.swing.JCheckBox();
        placeTXT = new javax.swing.JTextField();
        placeLBL = new javax.swing.JLabel();
        createResultBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        membersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        disciplinesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeLBL.setText("time");

        compBox.setText("comp");

        placeLBL.setText("place");

        createResultBTN.setText("Create Result");
        createResultBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResultBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createResultBTN)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLBL)
                            .addComponent(placeLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(compBox)
                            .addComponent(disciplinesComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(membersComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeTXT)
                            .addComponent(placeTXT))))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(membersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(disciplinesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLBL))
                .addGap(18, 18, 18)
                .addComponent(compBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placeLBL))
                .addGap(18, 18, 18)
                .addComponent(createResultBTN)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createResultBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResultBTNActionPerformed
        try {
            // TODO add your handling code here:
            String test = (String) membersComboBox.getModel().getSelectedItem();
            int memberID = Integer.parseInt(membersComboBox.getModel().getSelectedItem().toString().split(",")[0].trim());
            int disciplineID = Integer.parseInt(disciplinesComboBox.getModel().getSelectedItem().toString().split(",")[0].trim());
            String time = timeTXT.getText();
            String comp = "false";
            if (compBox.isSelected()) {
                comp = "true";
            }
            
            String place = placeTXT.getText();

            System.out.println(test);
            System.out.println("memberID: " + memberID);
            System.out.println("disciplineID: " + disciplineID);
            logic.createResult(memberID, disciplineID, time, comp, place);
            
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(resultsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createResultBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                resultsDialog dialog = new resultsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox compBox;
    private javax.swing.JButton createResultBTN;
    private javax.swing.JComboBox<String> disciplinesComboBox;
    private javax.swing.JComboBox<String> membersComboBox;
    private javax.swing.JLabel placeLBL;
    private javax.swing.JTextField placeTXT;
    private javax.swing.JLabel timeLBL;
    private javax.swing.JTextField timeTXT;
    // End of variables declaration//GEN-END:variables
}
